image: artifactory.wma.chs.usgs.gov/docker-official-mirror/ubuntu:focal

# These should be as SoC as possible.  Time is not an issue, legibility of errors is. 
stages: 
  - build image
  - build testspace
  - build test db
  - deployment

# Some templates to isolate jobs while reducing code
python_ubuntu_environment: &python_ubuntu_environment
  before_script
